import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Background from "./backgound/page"
import NavBar from "./navBar/page"
// import Objects from "./objects/Background"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const Mount = () =>{
      return Math.random() < 0.5;
  }
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
        <NavBar/>
        <Background/>
        {children}
        {/* {Mount? <Objects/> : null} */}
      </body>
    </html>
  );
}
